// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiC9MYw_F8urqjblRETr8C9DzghW5l2io',
    appId: '1:131702600145:web:b02604abdfdc02f495f0f0',
    messagingSenderId: '131702600145',
    projectId: 'student-register-1c21d',
    authDomain: 'student-register-1c21d.firebaseapp.com',
    storageBucket: 'student-register-1c21d.appspot.com',
    measurementId: 'G-WD821QT7TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtTrx3r_En1Zpgp102VhXIa1mt0HUpx0U',
    appId: '1:131702600145:android:f9363e11f3c40c3295f0f0',
    messagingSenderId: '131702600145',
    projectId: 'student-register-1c21d',
    storageBucket: 'student-register-1c21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHhxuF51nRZrzxfxsfIfoQgCK2FvoNTqg',
    appId: '1:131702600145:ios:6946294007b5a0bd95f0f0',
    messagingSenderId: '131702600145',
    projectId: 'student-register-1c21d',
    storageBucket: 'student-register-1c21d.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseStudentRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHhxuF51nRZrzxfxsfIfoQgCK2FvoNTqg',
    appId: '1:131702600145:ios:6946294007b5a0bd95f0f0',
    messagingSenderId: '131702600145',
    projectId: 'student-register-1c21d',
    storageBucket: 'student-register-1c21d.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseStudentRegisterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiC9MYw_F8urqjblRETr8C9DzghW5l2io',
    appId: '1:131702600145:web:30dea4d9c4d49db295f0f0',
    messagingSenderId: '131702600145',
    projectId: 'student-register-1c21d',
    authDomain: 'student-register-1c21d.firebaseapp.com',
    storageBucket: 'student-register-1c21d.appspot.com',
    measurementId: 'G-G2TRYDBNRV',
  );
}
